#!/usr/bin/env node
/**
 * Materializes the on-disk copies of the two Agent-Native Plan skills
 * (`visual-plan`, `visual-recap`) and their `references/*.md` files FROM the
 * single source of truth: the `BUILT_IN_APP_SKILLS["visual-plans"]` constant in
 * `packages/core/src/cli/skills.ts`.
 *
 * Those on-disk copies live in two location families per skill:
 *   1. `templates/plan/.agents/skills/<templateDir>/<relPath>`
 *   2. `skills/<exportedDir>/<relPath>`
 *
 * The copies were previously hand-maintained and drifted from the constant.
 * This script mirrors `sync-plan-marketplace.ts` and `sync-workspace-core-skills.ts`:
 * it writes by default and validates with `--check`, failing with a clear
 * "Run: pnpm sync:plan-skills" message when the committed tree drifts.
 *
 * The SKILL.md body is written VERBATIM from the constant — including its own
 * frontmatter `name:` field — because a separate test asserts byte-identity with
 * the constant. We never touch `.agents/skills/` directly (those are symlinks to
 * `skills/`), nor the plugin bundle / corpus (generated by other scripts).
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { BUILT_IN_APP_SKILLS } from "../packages/core/src/cli/skills.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "..");

const entry = BUILT_IN_APP_SKILLS["visual-plans"];

/** One Plan skill's source body, reference files, and on-disk target dir names. */
type PlanSkill = {
  /** Logical skill name, used to key into `entry.extraFiles`. */
  skill: string;
  /** SKILL.md body, written verbatim. */
  body: string;
  /** Reference files: skill-relative path -> content. */
  references: Record<string, string>;
  /** Dir name under `templates/plan/.agents/skills/`. */
  templateDir: string;
  /** Dir name under top-level `skills/`. */
  exportedDir: string;
};

const PLAN_SKILLS: PlanSkill[] = [
  {
    skill: "visual-plan",
    body: entry.skillMarkdown,
    references: entry.extraFiles?.["visual-plan"] ?? {},
    templateDir: "visual-plan",
    exportedDir: "visual-plans",
  },
  {
    skill: "visual-recap",
    body: entry.extraSkills?.["visual-recap"] ?? "",
    references: entry.extraFiles?.["visual-recap"] ?? {},
    templateDir: "visual-recap",
    exportedDir: "visual-recap",
  },
];

const check = process.argv.includes("--check");

/** A file the script wants committed: repo-relative path -> contents. */
type ExpectedFile = { rel: string; content: string };

/** Skill-relative file paths (SKILL.md + references), sorted for determinism. */
function skillRelPaths(plan: PlanSkill): { rel: string; content: string }[] {
  const files: { rel: string; content: string }[] = [
    { rel: "SKILL.md", content: plan.body },
  ];
  for (const rel of Object.keys(plan.references).sort()) {
    files.push({ rel, content: plan.references[rel] });
  }
  return files;
}

/** Both on-disk target dirs (absolute) for a Plan skill. */
function targetDirs(plan: PlanSkill): string[] {
  return [
    join(rootDir, "templates", "plan", ".agents", "skills", plan.templateDir),
    join(rootDir, "skills", plan.exportedDir),
  ];
}

function expectedFiles(): ExpectedFile[] {
  const files: ExpectedFile[] = [];
  for (const plan of PLAN_SKILLS) {
    const skillFiles = skillRelPaths(plan);
    for (const dir of targetDirs(plan)) {
      for (const { rel, content } of skillFiles) {
        files.push({ rel: relative(rootDir, join(dir, rel)), content });
      }
    }
  }
  return files;
}

/** Existing files inside a skill dir's `references/` subdir, repo-relative. */
function existingReferenceFiles(skillDir: string): string[] {
  const refDir = join(skillDir, "references");
  if (!existsSync(refDir)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const dirEntry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, dirEntry.name);
      if (dirEntry.isDirectory()) walk(abs);
      else if (dirEntry.isFile()) out.push(relative(rootDir, abs));
    }
  };
  walk(refDir);
  return out.sort();
}

function generate(files: ExpectedFile[]): void {
  // Prune stale reference files (a removed reference must not linger), but only
  // within each skill's `references/` subdir — never SKILL.md and never anything
  // outside these target dirs.
  const expectedSet = new Set(files.map((file) => file.rel));
  for (const plan of PLAN_SKILLS) {
    for (const dir of targetDirs(plan)) {
      for (const rel of existingReferenceFiles(dir)) {
        if (!expectedSet.has(rel)) {
          rmSync(join(rootDir, rel), { force: true });
        }
      }
    }
  }

  for (const file of files) {
    const abs = join(rootDir, file.rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, file.content, "utf-8");
  }
}

function checkInSync(files: ExpectedFile[]): void {
  const expectedSet = new Set(files.map((file) => file.rel));

  const missing = files
    .filter((file) => !existsSync(join(rootDir, file.rel)))
    .map((file) => file.rel);
  const changed = files
    .filter((file) => existsSync(join(rootDir, file.rel)))
    .filter(
      (file) => readFileSync(join(rootDir, file.rel), "utf-8") !== file.content,
    )
    .map((file) => file.rel);

  // Unexpected extra files only matter inside the `references/` subdirs we own.
  const extra: string[] = [];
  for (const plan of PLAN_SKILLS) {
    for (const dir of targetDirs(plan)) {
      for (const rel of existingReferenceFiles(dir)) {
        if (!expectedSet.has(rel)) extra.push(rel);
      }
    }
  }

  if (missing.length === 0 && extra.length === 0 && changed.length === 0) {
    return;
  }

  const sections: string[] = [];
  if (missing.length > 0)
    sections.push(`Missing:\n${missing.sort().join("\n")}`);
  if (extra.length > 0) sections.push(`Extra:\n${extra.sort().join("\n")}`);
  if (changed.length > 0)
    sections.push(`Changed:\n${changed.sort().join("\n")}`);
  throw new Error(
    `Plan skills are out of sync with BUILT_IN_APP_SKILLS["visual-plans"].\n\n${sections.join(
      "\n\n",
    )}\n\nRun: pnpm sync:plan-skills`,
  );
}

function main(): void {
  const files = expectedFiles();
  if (check) {
    checkInSync(files);
    console.log("Plan skills are in sync with skills.ts constants.");
  } else {
    generate(files);
    checkInSync(files);
    console.log("Synced Plan skills from skills.ts constants.");
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
